---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-${PV_INDEX}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /pv-${PV_INDEX}
    server: ${NFS_SERVER}
  persistentVolumeReclaimPolicy: Retain
